### ISSUE TITLE
CGSSetUniversalOwner

### ISSUE THREAD

**Issue by mischievous** [NUIKit/CGSInternal#5]
According to CGSConnection.h, sets a "Universal Owner" for the connection ID.  Currently, that owner is Dock.app.  

My theory was on Mojave
1) kill the dock like so "/bin/launchctl   load /System/Library/LaunchAgents/com.apple.Dock.plist; /bin/launchctl start com.apple.Dock.agent"

2) CGSMainConnectionID
2a) (Dock only)  _RegisterApplication

3) CGSNewConnection

4) CGSSetUniversalOwner with CID from step 2.

5) CGSSetOtherUniversalConnection using CID from step 2/step 3.

5a) Attempt to move a test window that I have open and know the WID of.  

6) re-launchctl the dock.  

That was the theory, looks almost exactly what the Dock app is actually doing. But it's not working.  

My questions...

1) Which OS did this work on for Skylight?  If I roll back to OS 10.x should it work?

2) Is there something I am missing?  

3) Is there an example someplace that works?  Maybe I am being mentally challenged.

4) Is there a contact at Apple that could tell me what I am doing wrong?

Thanks!

**Comment by jslegendre** [comment]
`CGSSetUniversalOwner` requires a private entitlement only Apple-signed binaries can have.

**Comment by mischievous** [comment]
@jslegendre thank you.  Apple is full of undocumented "helpful" security features.
