### ISSUE TITLE
CGSWindowTagBit

### ISSUE THREAD

**Issue by aleclarson** [NUIKit/CGSInternal#6]
How did you extract and verify the values of `CGSWindowTagBit`? I noticed some have changed since 2016, so I need the updated values. Cheers!

cc @avaidyam

**Comment by avaidyam** [comment]
Chances are they would not have changed as that would break internal or backwards compatibility support. The only way I know of verifying values for these bits is reverse engineering, unfortunately.

**Comment by CodaFi** [comment]
Run `strings` on SkyLight and grep for `TagBit` to get the full list.  There was a debug routine that would print a description of the window tag bits in CoreGraphics a few releases ago that I just fuzzed to extract the current values.
